# Generated by Django 2.2.7 on 2019-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comum',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
