# Generated by Django 2.2.7 on 2019-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_comum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientefixo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
