# Generated by Django 2.2.7 on 2019-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
