# Generated by Django 2.2.7 on 2019-12-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0002_peca_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='DescontoPeca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.Desconto')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.Peca')),
            ],
        ),
    ]
