# Generated by Django 2.2.7 on 2019-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0003_desconto_descontopeca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pecas', models.ManyToManyField(to='peca.Peca')),
            ],
        ),
    ]
