# Generated by Django 2.2.7 on 2019-12-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0005_carrinho_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaCarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='peca',
            name='codigo',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='pecas',
            field=models.ManyToManyField(to='peca.PecaCarrinho'),
        ),
        migrations.AddField(
            model_name='pecacarrinho',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.Peca'),
        ),
    ]
