# Generated by Django 2.2.7 on 2019-12-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0006_auto_20191204_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='user',
        ),
    ]
