# Generated by Django 2.2.7 on 2019-12-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0007_remove_carrinho_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='pecas',
        ),
        migrations.AddField(
            model_name='pecacarrinho',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peca.Carrinho'),
            preserve_default=False,
        ),
    ]
