# Generated by Django 2.2.7 on 2019-12-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0008_auto_20191212_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
