# Generated by Django 2.2.7 on 2019-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0009_auto_20191212_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.BooleanField(default=False)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='realizado',
        ),
    ]
